[package]
name = "telegram"
version = "0.1.0"
edition = "2024"

[dependencies]
grammers-client = "0.8.1"
grammers-mtsender = "0.8.1"
grammers-session = "0.8.0"
tokio = { version = "1.49.0", features = ["full"] }
publisher = { path = "../publisher" }
