[package]
name = "kol_follows"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
publisher = { path = "../../publisher" }
telegram_types = { path = "../../telegram_types" }

[features]
default = []         
production = []  