[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.49.0", features = ["full"] }

telegram = { path = "../engine/telegram" }
telegram_types = { path = "../engine/telegram_types" }
publisher = { path = "../engine/publisher" }
forwarder = { path = "../engine/listeners/forwarder" }
token_addressess_forwarder = { path = "../engine/listeners/token_addressess_forwarder" }
api = {path = "../engine/api"}
db = {path = "../engine/db"}