[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.49.0", features = ["full"] }

telegram = { path = "../engine/telegram" }
publisher = { path = "../engine/publisher" }
test_listener = { path = "../engine/test_listener" }
forwarder = { path = "../engine/forwarder" }