[package]
name = "lc_signals"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
publisher = { path = "../../publisher" }
regex = "1.12.3"
telegram_types = { path = "../../telegram_types" }
unicode-segmentation = "1.12.0"
