[package]
name = "analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
telegram_types = { path = "../../telegram_types" }
tokio = { version = "1.49.0", features = ["full"] }
publisher = { path = "../../publisher" }
dashmap = "6.1.0"
telegram = { path = "../../telegram"}