[package]
name = "errors_reporter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
publisher = { path = "../../publisher" }
telegram_types = { path = "../../telegram_types"}
telegram = { path = "../../telegram"}