[package]
name = "perp_kols"
version = "0.1.0"
edition = "2024"

[dependencies]
publisher = { path = "../../publisher" }
shared = {path = "../../shared"}
telegram_types = { path = "../../telegram_types" }
telegram = {path = "../../telegram"}